# to run the files use dvc.repro
stages:
  data_ingestion:
    cmd : python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw
    params:
      - data_ingestion.test_size # connecting the params files here (stage name in params file.parameter_name)

  data_preprocessing:
   cmd: python src/data_preprocessing.py
   deps:
    - src/data_preprocessing.py
    - data/raw # to link data_preprocessing and data_ingestion stages
   outs:
    - data/processed

  feature_engineering:
   cmd: python src/feature_engineering.py
   deps:
    - src/feature_engineering.py
    - data/processed # to link data_preprocessing and feature_engineering stages
   outs:
    - data/features
   params:
    - feature_engineering.max_features

  model_building:
   cmd: python src/model_building.py
   deps:
    - src/model_building.py
    - data/features
   outs:
    - model.pkl
   params:
    - model_building.n_estimators
    - model_building.learning_rate


  model_evaluation:
   cmd: python src/model_evaluation.py
   deps:
    - src/model_evaluation.py
    - data/features
    - model.pkl 
   metrics:
    - metrics.json