# to run the files use dvc.repro
stages:
  data_ingestion:
    cmd : python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
    outs:
      - data/raw
    params:
      - data_ingestion.test_size # connecting the params files here (stage name in params file.parameter_name)

  data_preprocessing:
   cmd: python src/data/data_preprocessing.py
   deps:
    - src/data/data_preprocessing.py
    - data/raw # to link data_preprocessing and data_ingestion stages
   outs:
    - data/interim

  feature_engineering:
   cmd: python src/features/feature_engineering.py
   deps:
    - src/features/feature_engineering.py
    - data/interim # to link data_preprocessing and feature_engineering stages
   outs:
    - data/processed
   params:
    - feature_engineering.max_features

  model_building:
   cmd: python src/models/model_building.py
   deps:
    - src/models/model_building.py
    - data/processed
   outs:
    - models/model.pkl
   params:
    - model_building.n_estimators
    - model_building.learning_rate


  model_evaluation:
   cmd: python src/models/model_evaluation.py
   deps:
    - src/models/model_evaluation.py
    - data/processed
    - models/model.pkl 
   metrics:
    - metrics.json